### PR TITLE
remove erroneous import in informatics __init__.py

### PR DESCRIPTION
**Pull request by Jammyzx1**
This will fix the install by the setup.py file by removing the erroneous import.

### CODE REVIEW

**Comment by Jammyzx1** [comment]
@jjasghar, @mmcelaney, @bradtopol, @MitchellRandom  is there any chance this can be merged? The install and code does not work as it currently stands due to the inclusion of a this erroneous import. Thanks.

**Comment by jjasghar** [comment]
This’ll have to be @MitchellRandom, the other three of us are org maintainers, not this repository maintainer.

**Comment by MitchellRandom** [comment]
I don't have any involvement with this repo.

**Comment by jjasghar** [comment]
Maybe @mfg75363?

**Comment by JamesLMcDonagh** [comment]
@jjasghar thanks, @mfg75363 has left the organisation (IBM) so I am wondering who can merge this correction now?

**Comment by jjasghar** [comment]
I'm looking internally for someone to take ownership of this repository. If I don't hear anything in the next couple days, I'll end up archiving it; and I strongly suggest you fork it into your own namespace.

**Comment by jjasghar** [comment]
Unfortunately, I wasn't able to find anyone to own this. I'll be archiving this repository, and if you'd like to continue using it I suggest you fork it and build off that.

**Pull request closed without merging**
